/*
 * REGISTERS.h
 *
 * THIS FILE WAS AUTOMATICALLY GENERATED BY /auto/project/bin/rdb2tt.pl
 * -config /home/rtseng/reg_generator/rdb2h.yml -db ./reg.db
 *
 */
#ifndef _REGISTERS_H_
#define _REGISTERS_H_

#if defined(CONFIG_ARCH_CA_VENUS)
  #include "ca8277b_registers.h"
#elif defined(CONFIG_ARCH_CA_MERCURY)
  #include "ca8299_registers.h"
#else
  #error "***** Not support the selected CONFIG_ARCH_xxx *****"
#endif


#endif /* end of _REGISTERS_H_ */
