dtb-$(CONFIG_ARCH_CA_VENUS) += ca8289-engboard.dts
dtb-$(CONFIG_ARCH_CA_VENUS) += ca8289-refboard.dts

dtb-$(CONFIG_ARCH_CA_MERCURY) += ca8299-fpga.dtb
dtb-$(CONFIG_ARCH_CA_MERCURY) += ca8299-engboard-A.dtb
dtb-$(CONFIG_ARCH_CA_MERCURY) += ca8299-engboard-A2.dtb
dtb-$(CONFIG_ARCH_CA_MERCURY) += ca8299-engboard-B.dtb
